/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-07-17 18:26:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import logic.engclasses.utils.Session;
import logic.engclasses.bean.LoggedBean;
import logic.controller.appcontroller.ViewProfile;
import logic.engclasses.bean.EventBean;

public final class HomepageArtists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("logic.engclasses.bean.LoggedBean");
    _jspx_imports_classes.add("logic.controller.appcontroller.ViewProfile");
    _jspx_imports_classes.add("logic.engclasses.utils.Session");
    _jspx_imports_classes.add("logic.engclasses.bean.EventBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
 
ViewProfile hac = new ViewProfile();
    
	
	Session sha = (Session)session.getAttribute("session");
	LoggedBean lbha = sha.getLoggedBean();
    String username = lbha.getUsername();
    EventBean eventname = hac.getLiveEvent(username);

 
      out.write("\r\n\r\n\r\n<!DOCTYPE html>\r\n<html  lang=\"it\">\r\n  <head>\r\n    <title>ShoowRome</title>\r\n  </head>\r\n  <body style=\"    height: 512px; background-color: white;\"><img src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/26362.png?raw=true\"\r\n\r\n \r\n\r\n      alt=\"\" style=\"width: 93px; height: 73px; margin-left: -2px;\"><br>\r\n    <h1 style=\"margin-top: -45.5667px; margin-left: 115px;\"> ShowRoome Performer </h1>\r\n    \r\n    <h1 style=\"margin-top:-58px; margin-left: 1150px;\">\r\n      \r\n    </h1>\r\n    <h1 style=\"margin-top:84px;margin-left:3px;\">\r\n       <form action=\"TastoChart\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:160px;\"><button name=\"Profile\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 570px;background-color: #4D4D4D;\">Chart</button>\r\n        </p>\r\n      </form>\r\n      <form action=\"TastoMap\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-180px;\"><button name=\"Profile\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 570px;background-color: #4D4D4D;\">Map</button>\r\n");
      out.write("        </p>\r\n      </form>\r\n      <form action=\"Homepage\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-555px;\"><button name=\"Profile\" style=\"height: 35px ; width: 95px; margin-top: -46px; margin-left: 570px;background-color: #4D4D4D;color:white;\">Homepage</button>\r\n        </p>\r\n      </form>\r\n      <form action=\"HostShowWebController\" method=\"get\">\r\n        <p style=\"margin-top:-74px;margin-left:937px;\"><button name=\"Proposte\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 210px;background-color: #4D4D4D;\">Proposte</button></p>\r\n      </form>\r\n    </h1>\r\n    <h1 style=\"margin-top: -74px;margin-left:px ;background-color: white;\">\r\n      <style>\r\n#rectangle {\r\n    width: 1250px;\r\n    height: 50px;\r\n    background: #10030F;\r\n}\r\n</style> <div id=\"rectangle\"></div>\r\n    </h1>\r\n              <h1 style=\"margin-top: -159px; margin-left: 1100px;\"> <input value=");
      out.print(username );
      out.write(" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1>\r\n      <form action=\"Logout\" method=\"post\" >          <h1 style=\"margin-left: 1190px;margin-top: -57px;\" > <input value=\"logout\" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1></form> \r\n    \r\n    <h1 style=\"margin-top: -20px; margin-left: 1170px;\">\r\n     \r\n    </h1>\r\n    <!-- Primo artista  -->\r\n    <p style=\"margin-top: 300px; margin-left: 5px;\"> <img  alt=\"\" src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/funny-male-mime-artist-with-makeup-gloves-hat_266732-7744.jpg?raw=true\"\r\n\r\n \r\n\r\n        style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label form=\"Descrizione artista\"></label></h2>\r\n    <ul>\r\n    <li style=\"list-style: none\">\r\n      <h3 style=\" margin-top: 120px;margin-left: 400px;\">\r\n        <ul>\r\n                             <button name=\"Dona\" style=\"height: 35px; width: 90px; margin-top: -200px; margin-left:75px; background-color: #4d4d4d;\"id=\"modifica\" onClick=\"modifica()\">Modifica</button>\r\n");
      out.write("      \r\n        <form action=\"UpdateInfo\" method=\"post\" style=\"margin-top: 10px;\">\r\n          <input disabled=\"true\"value=");
      out.print( lbha.getUsername() );
      out.write(" id=\"Nome\" name=\"Nome\" style=\"height: 25px; width: 225px;\"\r\n\r\n \r\n\r\n            type=\"text\">\r\n        </ul>\r\n        <ul>\r\n          <input disabled=\"true\" value=");
      out.print( lbha.getTalent() );
      out.write(" id=\"talent1\" name=\"talent1\"\r\n\r\n \r\n\r\n            style=\"height: 25px; width: 225px;\" type=\"text\">\r\n        </ul>\r\n        <ul>\r\n          <input disabled=\"true\" value=");
      out.print( lbha.getEmail() );
      out.write(" id=\"email1\" name=\"email1\"\r\n\r\n \r\n\r\n            style=\"height: 25px; width: 225px;\" type=\"text\"></input>\r\n            \r\n        </ul>\r\n         <input disabled=\"true\" value=");
      out.print( lbha.getDescription() );
      out.write(" id=\"descrizione1\" name=\"descrizione1\"\r\n\r\n \r\n\r\n            style=\"height: 25px; width: 225px;margin-left:40px;\" type=\"text\"></input>\r\n           \r\n      </h3>\r\n    </li>\r\n    </ul>\r\n    \r\n    \r\n    \r\n              <input  type=\"submit\" disabled=\"true\"  value =\"Salva\"  name=\"Salva\" id=\"Salva\" style=\"height: 35px; width: 90px; margin-top: 30px; margin-left:550px; background-color: #4d4d4d;\"id=\"salva\" ></button>\r\n            \r\n              <input  value=");
      out.print( lbha.getEmail() );
      out.write(" id=\"email\" name=\"email\"\r\n\r\n            style=\"height: 25px; width: 225px;margin-left:40px;display:none;\" type=\"text\"></input>\r\n              <input  value=");
      out.print( lbha.getTalent());
      out.write(" id=\"talent\" name=\"talent\"\r\n\r\n            style=\"height: 25px; width: 225px;margin-left:40px;display:none;\" type=\"text\"></input>\r\n              <input  value=");
      out.print( lbha.getDescription() );
      out.write(" id=\"descrizione\" name=\"descrizione\"\r\n\r\n            style=\"height: 25px; width: 225px;margin-left:40px;display:none;\" type=\"text\"></input>\r\n            \r\n            \r\n            </form>\r\n            \r\n             \r\n              <button  disabled=\"true\"  name=\"Dona\" style=\"height: 35px; width: 90px; margin-top: 30px; margin-left:550px; background-color: #4d4d4d;\"id=\"annulla\" onClick=\"annulla()\">Annulla</button>\r\n    \r\n  \r\n    <h2 style=\"margin-left:950px;margin-top: -380px;\">Le tue prenotazioni:</h2>\r\n      \r\n    \r\n    ");
if ((String)session.getAttribute("Hosting") != "noshow"){ 
      out.write("\r\n    <form action=\"Homepage\" method=\"get\">\r\n      <h3 style=\"margin-left:960px;margin-top: 0px;\">");
      out.print(eventname.getName() );
      out.write("</h3>\r\n    <button name=\"Informazioni\" style=\"height: 45px; width: 110px; margin-left: 1100px; background-color: #4d4d4d;margin-top: -80px;\">Dismiss</button>\r\n    </form>\r\n    ");
 }
      out.write("\t\r\n \r\n\r\n\r\n<script> \r\n   \r\n   function  modifica(){\r\n\t     \r\n\t\r\n\r\n\t     document.getElementById(\"descrizione1\").disabled =false;\r\n\t     document.getElementById(\"email1\").disabled =false;\r\n\t     document.getElementById(\"talent1\").disabled =false;\r\n\t     document.getElementById(\"annulla\").disabled =false;\r\n\t     document.getElementById(\"Salva\").disabled =false;\r\n\r\n\r\n\r\n   }\r\n\t\t </script>\r\n\t\t\r\n<script> \r\n   \r\n   function  annulla(){\r\n\tlocation.reload();\r\n\r\n\r\n\r\n   }\r\n\t\t </script>\r\n\r\n\r\n\r\n </body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n \r\n\r\n \r\n ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
