/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-07-17 18:26:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProfileSponsor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n<html  lang=\"it\">\r\n  <head>\r\n    <title>Prova</title>\r\n  </head>\r\n  <body style=\"    height: 512px; background-color: white;\"><img src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/26362.png?raw=true\"\r\n\r\n      alt=\"\" style=\"width: 93px; height: 73px; margin-left: -2px;\"><br>\r\n    <h1 style=\"margin-top: -45.5667px; margin-left: 115px;\"> ShowRoome Sponsor </h1>\r\n    <h1 style=\"margin-top: -60px; margin-left: 1000px;\"> <input value=\"\" size=\"18\"\r\n\r\n        maxlength=\"40\" type=\"text\"> </h1>\r\n    <h1 style=\"margin-top:-58px; margin-left: 1150px;\">\r\n      <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">\r\n        <input value=\"Search artist\" size=\"15\" maxlength=\"40\" ;style=\"background-color:\"\r\n\r\n#993300=\"\" type=\"submit\"></form>\r\n    </h1>\r\n    <h1 style=\"margin-top:84px;margin-left:3px;\">\r\n      <form action=\"TastoProfile\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:674px;\"><input id=\"Submit\" name=\"Profile\" type=\"submit\" value=\"Profile\" style=\"height: 35px; width: 95px; margin-top: -48px; margin-left: 160px;background-color: #4D4D4D;color:white;\"></input></p>\r\n");
      out.write("      </form>\r\n      <form action=\"TastoChart\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-right:2200;\"><input id=\"Submit\" name=\"Artisti\" type=\"submit\" value=\"Artisti\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 390px;background-color: #4D4D4D;\"></input>\r\n        </p>\r\n      </form>\r\n     \r\n      <form action=\"Homepage\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-555px;\"><input id=\"Submit\" name=\"Homepage\" type=\"submit\" value=\"Homepage\" style=\"height: 35px ; width: 95px; margin-top: -46px; margin-left: 570px;background-color: #4D4D4D;\"></input>\r\n        </p>\r\n      </form>\r\n      <form action=\"Tasto2servlet\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:937px;\"><input id=\"Submit\" name=\"Settings\" type=\"submit\" value=\"Settings\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 210px;background-color: #4D4D4D;\"></input></p>\r\n      </form>\r\n    </h1>\r\n    <h1 style=\"margin-top: -74px;margin-left:px ;background-color: white;\">\r\n");
      out.write("      <style>\r\n#rectangle {\r\n    width: 1250px;\r\n    height: 50px;\r\n    background: #10030F;\r\n}\r\n</style> <div id=\"rectangle\"></div>\r\n    </h1>\r\n    <h1 style=\"margin-top: -159px; margin-left: 1170px;\">\r\n      <form action=\"Login\" method=\"post\"><input\r\n\r\nvalue=\"Login\" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"></form>\r\n    </h1>\r\n    <!-- Primo artista  -->\r\n    <p style=\"margin-top: 300px; margin-left: 5px;\"> <img alt=\"\" src=\"https://www.cosafarearoma.it/wp-content/uploads/2014/06/Trinity-College-Irish-Pub-Roma.jpg\"\r\n   style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label ></label></h2>\r\n    <ul>\r\n    <li>\r\n      <h3 style=\" margin-top: px;margin-left: 500px;\">\r\n        <ul>\r\n          <input readonly=\"readonly\" value=\"Er Pubetto de zona\" id=\"Nome\" name=\"Nome\" style=\"height: 25px; width: 225px;\"\r\n\r\n            type=\"text\">\r\n        </ul>\r\n        <ul>\r\n          <input readonly=\"readonly\" value=\"Francesco Girardi\" id=\"Cognome\" name=\"Cognome\"\r\n");
      out.write("\r\n            style=\"height: 25px; width: 225px;\" type=\"text\">\r\n        </ul>\r\n        <ul>\r\n          <input readonly=\"readonly\" value=\"3347544448\" id=\"password\" name=\"password\"\r\n\r\n            style=\"height: 25px; width: 225px;\" type=\"text\">\r\n            \r\n        </ul>\r\n        \r\n           \r\n      </h3>\r\n    </li>\r\n     </ul>\r\n    <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">\r\n      <button name=\"Dona\" style=\"height: 35px; width: 90px; margin-top: -150px; margin-left: 615px; background-color: #4d4d4d;\">Modifica</button>\r\n    </form>\r\n    <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">\r\n      <button name=\"Informazioni\" style=\"height: 35px; width: 90px; margin-top: 20px; margin-left: 70px; background-color: #4d4d4d;\">Modifica\r\n        foto</button></form>\r\n    \r\n  </body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
