/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-07-17 18:26:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RegistrazioneSponsor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n    ");
 
String ids = (String)session.getAttribute("id_reg");

      out.write("\r\n<!DOCTYPE html>\r\n<html  lang=\"it\">\r\n  <head>\r\n    <title>ShoowRome</title>\r\n\t <body>\r\n  <style>\r\nbody {\r\n  background-image: url('https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/roma-2.jpg?raw=true');\r\n}\r\n</style>\r\n  </head>\r\n    <h1 style=\"margin-top: -45.5667px; margin-left: 115px;\"> ShowRoome </h1>\r\n    <p style=\"margin-top: -45.5667px; margin-left: 115px;\"> </p>\r\n    <h3 style=\" margin-top: 70px;margin-left: 480px;\">\r\n     <ul>\r\n             <label  name=\"login\" value=\"\" style=\"height: 60px; width: 150px; margin-top: 50px; margin-left:px;\">Selezionare: </label>\r\n    \r\n    </ul>\r\n    <form action=\"Registrazione\" method=\"post\">\r\n    <ul>\r\n        <button  value=\"User\" id=\"email\" name=\"id\" style=\"height: 25px; width: 60px;margin-top: -130px; margin-left:150px;\">User</button>\r\n      </ul>    \r\n\r\n \r\n\r\n  <ul>\r\n        <button  value=\"Performer\" id=\"email\" name=\"id\" style=\"height: 25px; width: 60px;margin-top: -150px; margin-left:150px; \">Artist</button>\r\n      </ul>\r\n      \r\n  <ul>\r\n        <button  value=\"Sponsor\" id=\"email\" name=\"id\" style=\"height: 25px; width: 60px;margin-top: -130px; margin-left:150px; color:white;\">Sponsor</button>\r\n");
      out.write("      </ul>\r\n    \r\n    </form>\r\n    \r\n    <form action=\"Registrazione\" method=\"get\">\r\n        <input  value=");
      out.print( ids );
      out.write(" id=\"username\" name=\"ids\" style=\"display:none; height: 25px; width: 225px;\">");
      out.print( ids );
      out.write("</input>\r\n    \r\n      <ul>\r\n        <input  value=\"Nome Utente\" id=\"username\" name=\"username\" style=\"height: 25px; width: 225px;\"type=\"text\"></input>\r\n      </ul>\r\n      <ul>\r\n        <input  value=\"password\" id=\"password\" name=\"password\"\r\n\r\n \r\n\r\n          style=\"height: 25px; width: 225px;\" type=\"text\"></input>\r\n      </ul>\r\n      <ul>\r\n        <input  value=\"activity\" id=\"activity\" name=\"param1\" style=\"height: 25px; width: 225px;\"\r\n    type=\"text\"></input>\r\n      </ul>\r\n         \r\n         <ul>\r\n        <input  value=\"descrizione\" id=\"email\" name=\"descrizione\" style=\"height: 25px; width: 225px;\"\r\n\r\n \r\n\r\n          type=\"text\"></input>\r\n          </ul> \r\n             <ul>\r\n        <input  value=\"capacity\" id=\"capacity\" name=\"param2\" style=\"height: 25px; width: 225px;\"type=\"text\"></input>\r\n          </ul>        \r\n           \r\n    </h3>\r\n      <button name=\"Informazioni\" style=\"height: 35px; width: 90px; margin-top: 60px; margin-left: 595px; background-color: #4d4d4d;\">Registrati</button></form>\r\n      \r\n     \r\n");
      out.write(" </form>\r\n \r\n\r\n \r\n\r\n  </body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
