/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-07-17 18:26:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import logic.engclasses.bean.SponsoredShowBean;
import java.util.List;
import java.util.ArrayList;
import logic.engclasses.utils.Session;
import logic.engclasses.bean.LoggedBean;

public final class UserSponsoredEvents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("logic.engclasses.bean.LoggedBean");
    _jspx_imports_classes.add("logic.engclasses.bean.SponsoredShowBean");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("logic.engclasses.utils.Session");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n    \r\n \r\n    \r\n\r\n    \r\n     \r\n\r\n    \r\n     \r\n");

Session sma = (Session)session.getAttribute("session");
LoggedBean lbma = sma.getLoggedBean();
String username = lbma.getUsername();
List<String> titles =  null;  //ssuc.buildShowStringArray();
String empty = "no";
try{
	titles.get(0);
} catch(Exception e){
	empty = "yes";
}


List<SponsoredShowBean> lssb = new ArrayList<>();
if(empty != "yes"){
for (int i=0; i<titles.size(); i++){
	//SponsoredShowBean ssb = ssuc.getSponsoredShow(titles.get(i));
	//lssb.add(ssb);

 }
}

      out.write("\r\n    \r\n<!DOCTYPE html>\r\n<html  lang=\"it\">\r\n\r\n\r\n  <head>\r\n   \r\n\r\n\r\n\r\n\r\n \r\n \r\n    <title>Prova</title>\r\n  </head>\r\n  <body style=\" height: 512px; background-color: white;\"><img src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/26362.png?raw=true\"\r\n\r\n\r\n      alt=\"\" style=\"width: 93px; height: 73px; margin-left: -2px;\"><br>\r\n   \r\n    <h1 style=\"margin-top: -45.5667px; margin-left: 115px;\">  ShowRoome</h1>  \r\n    \r\n\r\n\r\n       </h1>\r\n    \r\n    <h1 style=\"margin-top:84px;margin-left:3px;\">\r\n     \r\n      <form action=\"TastoChart\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:170px;\"><input id=\"Submit\" name=\"Chart\" type=\"submit\" value=\"Chart\" \" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 400px;background-color: #4D4D4D;\"></input>\r\n        </p>\r\n      </form>\r\n      <form action=\"TastoMap\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-170px;\"><input id=\"Submit\" name=\"Map\" type=\"submit\" value=\"Homepage\"  style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 220px; background-color: #4D4D4D;\"></input>\r\n");
      out.write("        </p>\r\n      </form>\r\n      \r\n      </form>\r\n      <form action=\"HostShowWebController\" method=\"get\">\r\n        <p style=\"margin-top:-74px;margin-left:937px;\"><input id=\"Submit\" type=\"submit\" name=\"Setting\" value=\"Sponsored\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 175px;color:white;background-color: #4D4D4D;\"></input></p>\r\n      </form>\r\n    </h1>\r\n    <h1 style=\"margin-top: -74px;margin-left:px ;background-color: white;\">\r\n      <style>\r\n#rectangle {âââââââ\r\n    width: 1250px;\r\n    height: 50px;\r\n    background: #10030F;\r\n}âââââââ\r\n</style> <div id=\"rectangle\"></div>\r\n    </h1>\r\n                      <h1 style=\"margin-top: -159px; margin-left: 1100px;\"> <input value=");
      out.print(username );
      out.write(" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1>\r\n             <form action=\"Logout\" method=\"post\">          <h1 style=\"margin-left: 1190px;margin-top: -57px;\" > <input value=\"logout\" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1></form> \r\n    \r\n");
   
String ok1 = "ok";
try{
	titles.get(0);
} catch(Exception e){
	ok1 = "no";
} 
      out.write("\r\n   \r\n    <!-- Primo artista  -->\r\n    \r\n   ");
 if(ok1=="ok"){ 
      out.write("\r\n    <p style=\"margin-top: 300px; margin-left: 5px;\"> <img alt=\"\" src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/churchill_arms.jpg?raw=true*/36\"\r\n\r\n\r\n        h1=\"\" style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label>");
      out.print( lssb.get(0).getTitle() );
      out.write("</label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">");
      out.print( lssb.get(0).getDescription() );
      out.write("</textarea></h3>\r\n\r\n <label style=\" margin-top: px;margin-left: 300px;\">");
      out.print( lssb.get(0).getArtist() );
      out.write("</label>\r\n     <label  style=\" margin-top: px;margin-left: 50px;\">");
      out.print( lssb.get(0).getLocation() );
      out.write("</label>\r\n\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n\r\n\r\n\r\n\r\n    ");
 } 
      out.write("\r\n <!--   <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">  <button name=\"Dona\" style=\"height: 35px; width: 90px; margin-top: -90px; margin-left: 1030px; background-color: #4d4d4d;\">Dona</button> </form>  --> \r\n  \r\n  ");
   
String ok2 = "ok";
try{
	titles.get(1);
} catch(Exception e){
	ok2 = "no";
} 
      out.write("\r\n  \r\n  ");
 if(ok2=="ok"){
      out.write("\r\n       <p style=\"margin-top: 300px; margin-left: 5px;\"> <img src=\"https://www.focusjunior.it/content/uploads/2018/10/Michelangelo-Buonarroti.jpg\"\r\n\r\n\r\n         h1=\"\" style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label form=\"Descrizione artista\">ciao</label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">\r\nArtista molto affermato nella puglia Borbonica gestiva uno spaccio di minori e prostituzione nei bordelli di tutta la cittÃ  noto anche con il nome di Scintilla O mast munnezz.\r\n</textarea></h3>\r\n\r\n <label form=\"Strada artista\" style=\" margin-top: px;margin-left: 300px;\"></label>\r\n     <label form=\"Tipo di artista\" style=\" margin-top: px;margin-left: 50px;\"></label>\r\n         <label form=\"Tipo di artista\" style=\" margin-top: px;margin-left: 50px;\"></label>\r\n\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n");
      out.write("  \r\n  \r\n  ");
 } 
      out.write("\r\n  \r\n  \r\n ");
  
 String ok3 = "ok";
 try{
	titles.get(2);
} catch(Exception e){
	ok3 = "no";
} 
      out.write("\r\n  \r\n  ");
 if(ok3=="ok"){
      out.write(" \r\n    <p style=\"margin-top: 300px; margin-left: 5px;\"> <img alt=\"\" src=\"https://www.focusjunior.it/content/uploads/2018/10/Michelangelo-Buonarroti.jpg\"\r\n\r\n\r\n         h1=\"\" style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label form=\"Descrizione artista\"></label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">\r\nArtista molto affermato nella puglia Borbonica gestiva uno spaccio di minori e prostituzione nei bordelli di tutta la cittÃ  noto anche con il nome di Scintilla O mast munnezz.\r\n</textarea></h3>\r\n\r\n <label form=\"Strada artista\" style=\" margin-top: px;margin-left: 300px;\"></label>\r\n     <label form=\"Tipo di artista\" style=\" margin-top: px;margin-left: 50px;\"></label>\r\n         <label form=\"Tipo di artista\" style=\" margin-top: px;margin-left: 50px;\"></label>\r\n\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n");
      out.write("  ");
 } 
      out.write("\r\n   <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">\r\n        <p style=\"margin-top:65px;margin-left:410px;\"><button  disabled=\"true\" name=\"Chart\" style=\"height: 35px; width: 95px; margin-top: -48px; margin-left: 160px;background-color: #4D4D4D;\">Vedi altri</button></p>\r\n      </form>\r\n    <h3 style=\"margin-top: -1225px; margin-left: 1000px;\"></h3>\r\n  \r\n\r\n\r\n\r\n \r\n  \r\n  </body>\r\n</html>\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
